import Head from 'next/head'

import Header from '../components/Header'
import Main from '../components/Main'
import Footer from '../components/Footer'

export async function getServerSideProps() {
  const res = await fetch('http://localhost:3000/api/resources')
  const json = await res.json()

  return {
    props: {
      restaurants: json.restaurants,
      cities: json.cities,
    },
  }
}

export default function Home(props) {
  const restaurants = props.restaurants[1]

  return (
    <div className="bg-gray-50 dark:bg-gray-900 min-h-screen">
      <Head>
        <title>McDonald's 🍔 статус в Черкасах</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;800&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Header />
      <Main restaurants={restaurants} />
      <Footer />
    </div>
  )
}
