import Head from 'next/head'
import Image from 'next/image'

export async function getServerSideProps() {
  const res = await fetch('http://localhost:3000/api/resources').then((res) =>
    res.json(),
  )

  return {
    props: {
      restaurants: res.restaurants,
      cities: res.cities,
    },
  }
}

export default function Home(props) {
  const restaurants = props.restaurants[1]
  console.log(props)

  return (
    <div className="bg-gray-50 dark:bg-gray-900 min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;800&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className="container w-full mx-auto py-8 min-h-[calc(100vh_-_65px)]">
        <h1 className="font-bold text-3xl md:text-5xl tracking-tight mb-1 text-black dark:text-white mb-8">
          McDonald's 🍔 статус в Черкасах
        </h1>
        <ul className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {restaurants.map((restaurant) => {
            // console.log(restaurant)
            return (
              <li
                className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-lg p-4"
                key={restaurant.item_id}
              >
                <span className="flex items-start">
                  <h2 className="text-lg w-fit inline md:text-lg font-medium mb-6 sm:mb-10 w-full text-gray-900 dark:text-gray-100 tracking-tight mr-2">
                    {restaurant.title}
                  </h2>
                  <div className="ml-auto flex gap-2">
                    <p className="text-2xl leading-none">🍔</p>
                    <img
                      className="rounded-full"
                      height={25}
                      width={25}
                      src={
                        'https://www.freelogovectors.net/svg07/glovo-logo.svg'
                      }
                    />
                  </div>
                </span>
                <p className="text-gray-700 dark:text-gray-400">
                  Адреса: {restaurant.address}
                </p>
                <p className="text-gray-700 dark:text-gray-400">
                  Час роботи: {restaurant.worktime}
                </p>
              </li>
            )
          })}
        </ul>
      </main>
      <footer className="container w-full mx-auto border-t border-gray-200 dark:border-gray-800 py-5 text-center">
        <p className="text-gray-500 hover:text-gray-600 transition">
          Made with 🍔 by Alex
        </p>
      </footer>
    </div>
  )
}
